### ISSUE TITLE
Fresh Multisite install is failing on v2 branch

### ISSUE THREAD

**Issue by mattbucci** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#46]
```
Warning: pg_query(): Query failed: ERROR:  relation "wp_options" does not exist
LINE 1: SELECT option_value FROM wp_options WHERE option_name = 'sit...
                                 ^ in /mnt/shared/sites/monad/wp-content/plugins/pg4wp/driver_pgsql.php on line 213
Fatal error: Uncaught Exception: Invalid or unsupported SQL statement. in /mnt/shared/sites/monad/wp-content/plugins/pg4wp/driver_pgsql_rewrite.php:26
Stack trace:
#0 /mnt/shared/sites/monad/wp-content/plugins/pg4wp/driver_pgsql_rewrite.php(40): createSQLRewriter('DESCRIBE wp_use...')
#1 /mnt/shared/sites/monad/wp-content/plugins/pg4wp/driver_pgsql.php(209): pg4wp_rewrite('DESCRIBE wp_use...')
#2 /mnt/shared/sites/monad/wp-content/plugins/pg4wp/core.php(54) : eval()'d code(2461): wpsql_query('DESCRIBE wp_use...', Object(PgSql\Connection))
#3 /mnt/shared/sites/monad/wp-content/plugins/pg4wp/core.php(54) : eval()'d code(2346): wpdb2->_do_query('DESCRIBE wp_use...')
#4 /mnt/shared/sites/monad/wp-content/plugins/pg4wp/core.php(54) : eval()'d code(3127): wpdb2->query('DESCRIBE wp_use...')
#5 /mnt/shared/sites/monad/wp-includes/functions.php(1815): wpdb2->get_results('DESCRIBE wp_use...')
#6 /mnt/shared/sites/monad/wp-includes/load.php(894): is_blog_installed()
#7 /mnt/shared/sites/monad/wp-settings.php(160): wp_not_installed()
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1363): require('/mnt/shared/sit...')
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1282): WP_CLI\Runner->load_wordpress()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#13 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('phar:///usr/loc...')
#14 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#15 {main}
  thrown in /mnt/shared/sites/monad/wp-content/plugins/pg4wp/driver_pgsql_rewrite.php on line 26
  ```

**Comment by mattbucci** [comment]
Failing SQL is `DESCRIBE wp_users;` there is currently no rewriter implementation for this.

**Comment by mattbucci** [comment]
this is because many rewrite functions are still in pgsql_install instead of standard rewriters and standard rewriters is called first. I'm migrating all these functions to standard rewriters
