### ISSUE TITLE
Test / Fix Solid Security plugin and add to list of supported plugins

### ISSUE THREAD

**Issue by mattbucci** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#79]
https://wordpress.org/plugins/better-wp-security/

Not working per: https://github.com/PostgreSQL-For-Wordpress/postgresql-for-wordpress/issues/73

**Comment by hahnn** [comment]
Tested today and still not working:

```
[Sun Mar 10 17:03:26.509013 2024] [php:error] [pid 21315] [client XX.XX.XX.XX:52366] PHP Fatal error:  Uncaught TypeError: iThemesSecurity\\User_Groups\\Repository\\DB_Repository::__construct(): Argument #1 ($wpdb) must be of type wpdb, wpdb2 given, called in wp-content/plugins/better-wp-security/core/modules/user-groups/container.php on line 26 and defined in wp-content/plugins/better-wp-security/core/modules/user-groups/Repository/DB_Repository.php:19\n
Stack trace:\n
#0 wp-content/plugins/better-wp-security/core/modules/user-groups/container.php(26): iThemesSecurity\\User_Groups\\Repository\\DB_Repository->__construct()\n
#1 wp-content/plugins/better-wp-security/vendor-prod/pimple/pimple/src/Pimple/Container.php(125): ITSEC_Modules::{closure}()\n
#2 wp-content/plugins/better-wp-security/core/modules/user-groups/container.php(22): iThemesSecurity\\Strauss\\Pimple\\Container->offsetGet()\n
#3 wp-content/plugins/better-wp-security/vendor-prod/pimple/pimple/src/Pimple/Container.php(125): ITSEC_Modules::{closure}()\n
#4 wp-content/plugins/better-wp-security/core/modules/user-groups/container.php(44): iThemesSecurity\\Strauss\\Pimple\\Container->offsetGet()\n
#5 wp-content/plugins/better-wp-security/vendor-prod/pimple/pimple/src/Pimple/Container.php(125): ITSEC_Modules::{closure}()\n
#6 wp-content/plugins/better-wp-security/vendor-prod/pimple/pimple/src/Pimple/Psr11/Container.php(51): iThemesSecurity\\Strauss\\Pimple\\Container->offsetGet()\n
#7 wp-content/plugins/better-wp-security/core/lib/validator.php(600): iThemesSecurity\\Strauss\\Pimple\\Psr11\\Container->get()\n
#8 wp-content/plugins/better-wp-security/core/lib/Config_Validator.php(71): ITSEC_Validator->validate_user_groups()\n
#9 wp-content/plugins/better-wp-security/core/modules/global/validator.php(18): iThemesSecurity\\Config_Validator->validate_settings()\n
#10 wp-content/plugins/better-wp-security/core/lib/validator.php(63): ITSEC_Global_Validator->validate_settings()\n
#11 wp-content/plugins/better-wp-security/core/lib/settings.php(284): ITSEC_Validator->validate()\n
#12 wp-content/plugins/better-wp-security/core/lib/settings.php(267): ITSEC_Settings->set_all()\n
#13 wp-content/plugins/better-wp-security/core/modules.php(359): ITSEC_Settings->set()\n
#14 wp-content/plugins/better-wp-security/core/setup.php(76): ITSEC_Modules::set_setting()\n
#15 wp-content/plugins/better-wp-security/core/core.php(626): ITSEC_Setup::handle_upgrade()\n
#16 wp-includes/class-wp-hook.php(322): ITSEC_Core->handle_upgrade()\n
#17 wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()\n
#18 wp-includes/plugin.php(517): WP_Hook->do_action()\n
#19 wp-settings.php(506): do_action()\n
#20 wp-config.php(96): require_once('...')\n
#21 wp-load.php(50): require_once('...')\n
#22 wp-admin/admin.php(34): require_once('...')\n
#23 wp-admin/plugins.php(10): require_once('...')\n
#24 {main}\n  thrown in wp-content/plugins/better-wp-security/core/modules/user-groups/Repository/DB_Repository.php on line 19, referer: https://www.XXXXXXXXXXXXX.XX/wp-admin/plugins.php
```
